//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Geonorge.TiltaksplanApi.Application.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ValidationResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ValidationResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Geonorge.TiltaksplanApi.Application.Resources.ValidationResource", typeof(ValidationResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tidsrom for slutt av gjennomføringsslutt må være en gyldig dato.
        /// </summary>
        internal static string ImplementationEnd {
            get {
                return ResourceManager.GetString("ImplementationEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tidsrom for gjennomføringsslutt kan ikke være før tidsrom for gjennomføringsstart.
        /// </summary>
        internal static string ImplementationEndBeforeImplementationStart {
            get {
                return ResourceManager.GetString("ImplementationEndBeforeImplementationStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tidsrom for gjennomføringsstart må være en gyldig dato.
        /// </summary>
        internal static string ImplementationStart {
            get {
                return ResourceManager.GetString("ImplementationStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;Culture&apos; må fylles ut.
        /// </summary>
        internal static string LanguageCulture {
            get {
                return ResourceManager.GetString("LanguageCulture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;Navn&apos; må fylles ut.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;Nummer&apos; må fylles ut.
        /// </summary>
        internal static string Number {
            get {
                return ResourceManager.GetString("Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Det finnes allerede en aktivitet registrert med nummeret {0}.
        /// </summary>
        internal static string NumberUniqueActivity {
            get {
                return ResourceManager.GetString("NumberUniqueActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Det finnes allerede et tiltak registrert med nummeret {0}.
        /// </summary>
        internal static string NumberUniqueMeasure {
            get {
                return ResourceManager.GetString("NumberUniqueMeasure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;Eier&apos; må fylles ut.
        /// </summary>
        internal static string Owner {
            get {
                return ResourceManager.GetString("Owner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minst én deltaker må legges til.
        /// </summary>
        internal static string Participants {
            get {
                return ResourceManager.GetString("Participants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;Ansvarlig etat&apos; må fylles ut.
        /// </summary>
        internal static string ResponsibleAgency {
            get {
                return ResourceManager.GetString("ResponsibleAgency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;Konkrete resultater&apos; må være mellom 1 og 5.
        /// </summary>
        internal static string Results {
            get {
                return ResourceManager.GetString("Results", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;Status&apos; må fylles ut.
        /// </summary>
        internal static string StatusActivity {
            get {
                return ResourceManager.GetString("StatusActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;Status&apos; må være mellom 1 og 5.
        /// </summary>
        internal static string StatusMeasure {
            get {
                return ResourceManager.GetString("StatusMeasure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;Tittel&apos; må fylles ut.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;Trafikklys&apos; må være mellom 1 og 3.
        /// </summary>
        internal static string TrafficLight {
            get {
                return ResourceManager.GetString("TrafficLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;Volum&apos; må være mellom 0 og 5.
        /// </summary>
        internal static string Volume {
            get {
                return ResourceManager.GetString("Volume", resourceCulture);
            }
        }
    }
}
