// <auto-generated />
using System;
using Geonorge.TiltaksplanApi.Infrastructure.DataModel;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Geonorge.TiltaksplanApi.Infrastructure.Migrations
{
    [DbContext(typeof(MeasurePlanContext))]
    [Migration("20201117130737_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("dbo")
                .HasAnnotation("ProductVersion", "3.1.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Geonorge.TiltaksplanApi.Domain.Models.Activity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("ImplementationEnd")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ImplementationStart")
                        .HasColumnType("datetime2");

                    b.Property<int>("MeasureId")
                        .HasColumnType("int");

                    b.Property<int>("ResponsibleAgencyId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MeasureId");

                    b.HasIndex("ResponsibleAgencyId")
                        .IsUnique();

                    b.ToTable("Activities");
                });

            modelBuilder.Entity("Geonorge.TiltaksplanApi.Domain.Models.ActivityTranslation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ActivityId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LanguageCulture")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ActivityId");

                    b.HasIndex("LanguageCulture");

                    b.ToTable("ActivityTranslations");
                });

            modelBuilder.Entity("Geonorge.TiltaksplanApi.Domain.Models.Language", b =>
                {
                    b.Property<string>("Culture")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Culture");

                    b.ToTable("Languages");
                });

            modelBuilder.Entity("Geonorge.TiltaksplanApi.Domain.Models.Measure", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("OwnerId")
                        .HasColumnType("int");

                    b.Property<int?>("Results")
                        .HasColumnType("int");

                    b.Property<int?>("Status")
                        .HasColumnType("int");

                    b.Property<int?>("TrafficLight")
                        .HasColumnType("int");

                    b.Property<int?>("Volume")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId")
                        .IsUnique();

                    b.ToTable("Measures");
                });

            modelBuilder.Entity("Geonorge.TiltaksplanApi.Domain.Models.MeasureTranslation", b =>
                {
                    b.Property<int>("MeasureId")
                        .HasColumnType("int");

                    b.Property<string>("LanguageCulture")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Progress")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MeasureId", "LanguageCulture");

                    b.HasIndex("LanguageCulture");

                    b.ToTable("MeasureTranslations");
                });

            modelBuilder.Entity("Geonorge.TiltaksplanApi.Domain.Models.Organization", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("OrgNumber")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("Organizations");
                });

            modelBuilder.Entity("Geonorge.TiltaksplanApi.Domain.Models.Participant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ActivityId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("OrganizationId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ActivityId");

                    b.HasIndex("OrganizationId")
                        .IsUnique()
                        .HasFilter("[OrganizationId] IS NOT NULL");

                    b.ToTable("Participants");
                });

            modelBuilder.Entity("Geonorge.TiltaksplanApi.Domain.Models.Activity", b =>
                {
                    b.HasOne("Geonorge.TiltaksplanApi.Domain.Models.Measure", null)
                        .WithMany("Activities")
                        .HasForeignKey("MeasureId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Geonorge.TiltaksplanApi.Domain.Models.Organization", "ResponsibleAgency")
                        .WithOne()
                        .HasForeignKey("Geonorge.TiltaksplanApi.Domain.Models.Activity", "ResponsibleAgencyId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("Geonorge.TiltaksplanApi.Domain.Models.ActivityTranslation", b =>
                {
                    b.HasOne("Geonorge.TiltaksplanApi.Domain.Models.Activity", null)
                        .WithMany("Translations")
                        .HasForeignKey("ActivityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Geonorge.TiltaksplanApi.Domain.Models.Language", "Language")
                        .WithMany()
                        .HasForeignKey("LanguageCulture")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Geonorge.TiltaksplanApi.Domain.Models.Measure", b =>
                {
                    b.HasOne("Geonorge.TiltaksplanApi.Domain.Models.Organization", "Owner")
                        .WithOne()
                        .HasForeignKey("Geonorge.TiltaksplanApi.Domain.Models.Measure", "OwnerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("Geonorge.TiltaksplanApi.Domain.Models.MeasureTranslation", b =>
                {
                    b.HasOne("Geonorge.TiltaksplanApi.Domain.Models.Language", "Language")
                        .WithMany()
                        .HasForeignKey("LanguageCulture")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Geonorge.TiltaksplanApi.Domain.Models.Measure", null)
                        .WithMany("Translations")
                        .HasForeignKey("MeasureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Geonorge.TiltaksplanApi.Domain.Models.Participant", b =>
                {
                    b.HasOne("Geonorge.TiltaksplanApi.Domain.Models.Activity", null)
                        .WithMany("Participants")
                        .HasForeignKey("ActivityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Geonorge.TiltaksplanApi.Domain.Models.Organization", "Organization")
                        .WithOne()
                        .HasForeignKey("Geonorge.TiltaksplanApi.Domain.Models.Participant", "OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
